### ISSUE TITLE
ClientDelay seems to be incorrectly processed

### ISSUE THREAD

**Issue by bergerch** [Delphi-BFT/tool#16]
In ``orchestrator.js`` a template should be created where the ``start_time`` of client processes is set to ``clientDelay`` as described in the experimental description file.

```
shadowTemplate = await createShadowHostConfig(
      shadowTemplate,
      hosts,
      e[experimentId].misc.clientDelay
);
```

but then ``createShadowHostConfig``seems to ignore the passed ``clientDelay`` param:

```
async function createShadowHostConfig(
  shadowTemplate,
  replicas,
  clientDelay
) {
  for (let i = 0; i < replicas.length; i++) {
    shadowTemplate = yg.makeHost(
      shadowTemplate,
      replicas[i].name,
      replicas[i].ip,
      i,
      replicas[i].procs
    );
  }
  return shadowTemplate;
}
```

the resulting conf file always has a ``start_time: 0`` even if ``clientDelay`` is specified. This seems to bug experiments with BFT-SMaRt if clients send requests before replicas are ready.

Edit: Not sure if this bug was fixed in the meantime, I am a little behind the most recent main branch. (Feel free to close if it is fixed now)

**Comment by bentoumia** [comment]
@bergerch good catch :D this was fixed, use exp.client.startTime (optional; default: 0) instead see: https://github.com/Delphi-BFT/tool/blob/b3d912f1f8b364aec0d504d4b143993faed55684/examples/serial22/bftsmart-AWS.yaml#L32

**Comment by bentoumia** [comment]
Closing as its fixed.
