### ISSUE TITLE
Shadow does not seem to terminate JVM correctly

### ISSUE THREAD

**Issue by bergerch** [Delphi-BFT/tool#17]
Even after a simulation completes, the Java processes seem to be still running. Possible workaround for now: ``killall java`` after completion of the bftsmart simulation. (i.e. in getStats() of the bftsmart connector? or at some callback that is invoked when the simulation completes but before the start of the next simulation)

**Comment by bentoumia** [comment]
Thanks for reporting :D i was unaware of this. Will look into it.
