### ISSUE TITLE
Update examples/serial22/ yaml format to work after refactoring merge

### ISSUE THREAD

**Issue by bergerch** [Delphi-BFT/tool#18]
Currently [examples](https://github.com/Delphi-BFT/tool/tree/main/examples)/serial22/ needs some modifications:
- Update format to work after refactoring
- Predefined plots can be removed from the hotstuff examples

**Comment by bentoumia** [comment]
EDFs Fixed. Sorry for the delay, i had to run sims for validation :D.

Will fix predefinedPlots today :)

**Comment by bentoumia** [comment]
Fixed second point @bergerch see 287ae2ebadeb4ee1fb50e211d12eae22ab5314f3

users may now specify files with predefined datasets OR specify plots inline as it was done now:

ex: https://github.com/Delphi-BFT/tool/blob/main/examples/serial22/hs-p1024.yaml
