### ISSUE TITLE
Installation Script

### ISSUE THREAD

**Issue by bergerch** [Delphi-BFT/tool#2]
Maybe we can create a script ```install.sh``` which installs a dependencies assuming a plain Ubuntu 20.04 machine, in particular:

- node, npm and all of our needed packages
- Phantom and its dependencies
- dependencies of BFT-SMaRt, HotStuff and Themis

So that a user just needs to invoke the script and is ready to run the first experiments

**Comment by bentoumia** [comment]
Done with Ansible, checkout README for specifics :D.

Closing.
