### ISSUE TITLE
Update EDFs for workshop submission

### ISSUE THREAD

**Issue by bergerch** [Delphi-BFT/tool#28]
The EDFs in /examples/dicg22

will not work anymore, because packet_loss: NaN error.

Is it sufficient to add packet_loss 0.0 to network options?

We should check if these EDFs run fine, they should never break because this is important for our submission

**Comment by bentoumia** [comment]
Yes one should add packetLoss (camelCase) to network options for each experiment. 

should be fixed 6e193f476bef527d85f0cf791203d84912c1adae.

Please test again and close the issue if everything is working :D
